[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
# (Optional) Text in landing page button
LANDING_BUTTON = "Poke around the notes 👆"
# (Optional) Site description on landing page
LANDING_DESCRIPTION = "Knarl & Keppuc insisted I learn to write, and then they kept asking for all those boring debriefing homeworks. So here's the best dragon's library notes. Do I get a cookie yet? Pistachio rose cooke?"
# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "DndTheLibrary/001-Library-Homepage"
# (Optional) Site title on landing page
LANDING_TITLE = "Chance for Treasurer! ...no, wait... Vote More Treasure for Chance! 💖"
PYTHON_VERSION = "3.8"
# (REQUIRED) Site repo URL
REPO_URL = "https://github.com/Jahteo/DndTheLibraryRepo"
# (Optional) Site title in navbar
SITE_TITLE = "The Library Notes"
# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)
SITE_TITLE_TAB = "Bestest Dragon"
# (REQUIRED) Netlify site URL
SITE_URL = "https://thelibrarynotes.netlify.app/"
# (Optional) Site Timezone
# TIMEZONE = "Asia/Hong_Kong"
ZOLA_VERSION = "0.15.2"
# (Optional, default title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.
SORT_BY = "title"
# (Optional) Google Analytics Measurement ID
GANALYTICS = ""
# (Optional, default true) Slugify URLs. Put "" to disable.
SLUGIFY = "y"
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
HOME_GRAPH = "y"
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
PAGE_GRAPH = "y"
# Page graph only shows directly connected nodes. Default: "".
LOCAL_GRAPH = "y"
# If "y", clicking on graph link replaces current tab. Else, page is opened in new tab. Default: "".
GRAPH_LINK_REPLACE = ""
# (Optional, default false) Whether sidebar sections should be collapsed by default.
SIDEBAR_COLLAPSED = ""
